In [3]:
import numpy as np 
from scipy.io import loadmat

import import_ipynb
from Hamiltonian_solver import *

# mat_data = generate_magnetic_field_sensitivity(4.2049)

# print(mat_data)
import numpy as np
from scipy.io import loadmat

# mat_data = hfs.generate_magnetic_field_sensitivity(4.2075) #loadmat('sensitivity_matrix_4p2095G.mat')

# matrix_sen_24x5 = mat_data['S']

# matrix_sen_24x5[matrix_sen_24x5 == 0] = np.nan
# def get_sen(transitions,matrix = mat_data):
#     pi_times_list = []
#     col_labels = [-2, -1, 0, 1, 2]
#     for transition in transitions:
#         row_label = [transition[1],transition[2]]
#         Fs = [1,2,3,4]
#         states = []
#         for i in Fs:
#             for j in range(2*i+1):
#                 mF = i-j
#                 states.append([i,mF])
    
#         row_labels = states
    
#         col_label = transition[0]
    
#         # Find the index of the row label
#         row_index = next((i for i, label in enumerate(row_labels) if label == row_label), None)
#         # Find the index of the column label
#         col_index = col_labels.index(col_label)
        
#         if row_index is not None and col_index in range(len(col_labels)):
#             pi_times_list.append(matrix[row_index, col_index])
#         else:
#             pi_times_list.append(np.nan)

#     return pi_times_list


# # get_sen([[0,2,0],[-1,4,-3],[-2,4,-4]],mat_data)
# an1_mat = (mat_data - get_sen([[0,2,0]])[0])/(get_sen([[0,4,-2]])[0] -  get_sen([[0,2,0]])[0])

transition_strengths = np.array([[np.nan, 0.0563, 0.055, 0.0519, 0.0341],
                        [0.0753, 0.0246, 0.0096, 0.0336, 0.056],
                        [0.053, 0.0598, 0.047, 0.0355, np.nan],
                        [np.nan, np.nan, 0.1103, 0.1061, 0.0819],
                        [np.nan, 0.1273, 0.0275, 0.0613, 0.0981],
                        [0.0973, 0.0635, 0.0919, 0.0258, 0.0932],
                        [0.1163, 0.0281, 0.0575, 0.107, np.nan],
                        [0.1105, 0.1056, 0.0814, np.nan, np.nan],
                        [np.nan, np.nan, np.nan, 0.2813, 0.0091],
                        [np.nan, np.nan, 0.2288, 0.1549, 0.0415],
                        [np.nan, 0.1517, 0.2135, 0.0697, 0.0446],
                        [0.0763, 0.2008, 0.1741, 0.003, 0.0359],
                        [0.1367, 0.2351, 0.0773, 0.039, np.nan],
                        [0.2241, 0.1763, 0.0106, np.nan, np.nan],
                        [0.268, 0.0634, np.nan, np.nan, np.nan],
                        [np.nan, np.nan, np.nan, np.nan, 0.3278],
                        [np.nan, np.nan, np.nan, 0.0828, 0.268],
                        [np.nan, np.nan, 0.0019, 0.1664, 0.234],
                        [np.nan, 0.025, 0.0679, 0.2278, 0.1523],
                        [0.0232, 0.001, 0.156, 0.2077, 0.0915],
                        [0.0309, 0.0593, 0.206, 0.1694, np.nan],
                        [0.0276, 0.1438, 0.2401, np.nan, np.nan],
                        [0.0094, 0.2862, np.nan, np.nan, np.nan],
                        [0.3278, np.nan, np.nan, np.nan, np.nan]])

import numpy as np

transition_strengths = np.loadtxt('Z:\Lab Data\Phase_and_freq_correction_180Hz\Transition_strengths_4p216.txt',delimiter=',')  # Assumes space-delimited file
transition_strengths[transition_strengths == 0] = np.nan
# print(transition_strengths)


pi_t = [18.622, 31.746, 37.865, 27.596, 36.429]
strengths = np.array([transition_strengths[23,0],transition_strengths[14,0],transition_strengths[17,4],transition_strengths[16,4],transition_strengths[15,4]])
pitime_n2 = pi_t[0] # [-2, 4, -4]
pitime_n1 = pi_t[1] # [-2, 3, -3]
pitime_0 = pi_t[2] # [2, 4, 2]
pitime_p1 = pi_t[3] # [2, 4, 3]
pitime_p2 = pi_t[4] # [2, 4, 4]

pi_t = np.array([pitime_n2,pitime_n1,pitime_0,pitime_p1,pitime_p2])
factors = pi_t * strengths
Fs = [1,2,3,4]
row_labels = []
for i in Fs:
    for j in range(2*i+1):
        mF = i-j
        row_labels.append([i,mF])
col_labels = [-2, -1, 0, 1, 2]

pi_times = np.zeros((24,5))
for i in range(np.shape(transition_strengths)[0]):
    for j in range(np.shape(transition_strengths)[1]):
        # print(i,j)
        if not np.isnan(transition_strengths[i,j]):

            delta_m = (row_labels[i][1]-col_labels[j])+2

            pi_times[i,j] = factors[delta_m]/transition_strengths[i,j]
print(pi_times)
def get_pi_times(transitions,matrix = pi_times):
    pi_times_list = []
    for transition in transitions:
        row_label = [transition[1],transition[2]]
        Fs = [1,2,3,4]
        states = []
        for i in Fs:
            for j in range(2*i+1):
                mF = i-j
                states.append([i,mF])
    
        row_labels = states
    
        col_label = transition[0]
    
        # Find the index of the row label
        row_index = next((i for i, label in enumerate(row_labels) if label == row_label), None)
        # Find the index of the column label
        col_index = col_labels.index(col_label)
        
        if row_index is not None and col_index in range(len(col_labels)):
            pi_times_list.append(matrix[row_index, col_index])
        else:
            pi_times_list.append(np.nan)

    return pi_times_list

def get_pulse_schedule(rabi_freqs, fractions):
    if len(rabi_freqs) != len(fractions):
        raise ValueError("rabi_freqs and fractions must have the same length.")
    
    times = []
    t_current = 0.0  # microseconds (start at time=0)
    
    for Omega, frac in zip(rabi_freqs, fractions):
        if not 0 <= frac <= 1:
            raise ValueError(f"Fraction must be between 0 and 1, got {frac}.")
        
        # Calculate the rotation angle and the pulse duration
        theta = 2.0 * np.arcsin(np.sqrt(frac))   # in radians
        t_pulse = theta / Omega if Omega > 0 else 0.0  # microseconds (if Omega in MHz)
        
        # The pulse starts at t_current, ends at t_current + t_pulse
        t_start = t_current
        t_end = t_current + t_pulse
        
        times.append((t_start, t_end))
        t_current = t_end  # next pulse starts after this one finishes
    
    return times

# mat_data = generate_magnetic_field_sensitivity(4.2049)

# matrix_sen_24x5 = generate_magnetic_field_sensitivity(4.2049)

# matrix_sen_24x5[np.isnan(transition_strengths)] = np.nan
# np.savetxt('sensitivities_4p216.txt',matrix_sen_24x5, delimiter=',')
sens_matrix = np.loadtxt('Z:\Lab Data\Phase_and_freq_correction_180Hz\sensitivities_4p216.txt',delimiter=',')
print(sens_matrix)

[[   0.          211.9322501   134.46824927  170.80710206  249.8197383 ]
 [ 158.67999176  301.16549727  921.45526918  253.17624047  108.98500926]
 [ 139.52333084  148.14607451  181.16403349  171.87311245    0.        ]
 [   0.            0.          108.23055675   69.68854243  108.16046645]
 [   0.           93.77573445  268.8374713   144.6413757    86.74807471]
 [ 122.70543703  116.4129164    96.40360429  329.79550561   65.47951644]
 [  63.61091827  314.75453041  147.92715683   57.05244149    0.        ]
 [  80.1717235    80.57107542   75.00681767    0.            0.        ]
 [   0.            0.            0.           42.44279842  816.89796011]
 [   0.            0.           52.18745061   47.73855147  213.54373172]
 [   0.           78.71729484   34.64748359  127.12049517  190.86212989]
 [ 156.52264106   36.83116196   50.89949487 2802.28634035  170.05153014]
 [  54.1229026    37.67897927  110.12364584  156.61516797    0.        ]
 [  39.54078846   48.26913817  577.36344243    0.  

In [4]:
def assign_states(transitions):
    unique_states = {}
    state_counter = 0

    # for path in transitions:
    for transition in transitions:
        from_state = (transition[0],)
        to_state = tuple(transition[1:])
        if from_state not in unique_states:
            unique_states[from_state] = state_counter
            state_counter += 1
        if to_state not in unique_states:
            unique_states[to_state] = state_counter
            state_counter += 1

    return unique_states

def translate_transitions(transitions, unique_states):
    all_couplings = []

    translated_path = []
    for transition in transitions:
        from_state = (transition[0],)
        to_state = tuple(transition[1:])
        translated_from = unique_states[from_state]
        translated_to = unique_states[to_state]
        translated_path.append((translated_from, translated_to))
        all_couplings.append((translated_from, translated_to))

    return all_couplings